/**
 * arbitContract.js — ArbitCore Smart Contract Service
 *
 * Imports the ABI and deployed address from ../abi/ArbitCore.json (generated
 * by hardhat/scripts/deploy.js after a successful deployment).
 *
 * Falls back to VITE_CONTRACT_ADDRESS env var if set, which takes priority.
 * Throws a clear error on startup if neither is a valid Ethereum address.
 */

import { ethers } from 'ethers';
import { HASHKEY_RPC } from './evmWallet';

// ── Load ABI + address from the deploy artifact ─────────────────────────────
let ArbitCoreArtifact = { address: '', abi: [] };
try {
    // This import will resolve at build time once deploy.js has created the file.
    const module = await import('../abi/ArbitCore.json', { assert: { type: 'json' } });
    ArbitCoreArtifact = module.default;
} catch (_) {
    // File not generated yet (pre-deployment). Will fall back to env var below.
    console.warn('[ArbitContract] src/abi/ArbitCore.json not found — falling back to VITE_CONTRACT_ADDRESS');
}

// ── Resolve address: env var takes priority over artifact ────────────────────
const CONTRACT_ADDRESS = (
    import.meta.env.VITE_CONTRACT_ADDRESS ||
    ArbitCoreArtifact.address ||
    ''
).trim();

// ── Startup validation ───────────────────────────────────────────────────────
const EVM_ADDRESS_RE = /^0x[0-9a-fA-F]{40}$/;
if (!CONTRACT_ADDRESS || !EVM_ADDRESS_RE.test(CONTRACT_ADDRESS)) {
    throw new Error(
        `ArbitCore contract address is not configured — check .env (VITE_CONTRACT_ADDRESS) ` +
        `or ensure src/abi/ArbitCore.json has been generated by the deploy script. ` +
        `Got: "${CONTRACT_ADDRESS}"`
    );
}

// Use ABI from artifact if available, otherwise use the minimalist inline ABI
const ABI = ArbitCoreArtifact.abi?.length > 0
    ? ArbitCoreArtifact.abi
    : [
        // Core Write Functions
        "function createProject(uint256 threshold) external payable returns (uint256 projectId)",
        "function submitMilestoneProof(uint256 projectId, string calldata proof) external",
        "function submitAIScore(uint256 projectId, uint256 score, bytes calldata signature) external",
        "function releaseFunds(uint256 projectId) external",
        "function refund(uint256 projectId) external",

        // Admin
        "function setOracle(address newOracle) external",

        // View Functions
        "function getProject(uint256 projectId) external view returns (tuple(address creator, uint256 funds, uint256 score, uint256 threshold, string proof, bool isScored, bool isReleased))",
        "function isActive(uint256 projectId) external view returns (bool)",

        // Events
        "event ProjectCreated(uint256 indexed projectId, address indexed creator, uint256 funds, uint256 threshold)",
        "event ProofSubmitted(uint256 indexed projectId, string proof)",
        "event ScoreSubmitted(uint256 indexed projectId, uint256 score, bool passed)",
        "event FundsReleased(uint256 indexed projectId, address indexed creator, uint256 amount)",
        "event FundsRefunded(uint256 indexed projectId, address indexed creator, uint256 amount)"
    ];

export { CONTRACT_ADDRESS };

console.log('[ArbitContract] Using contract address:', CONTRACT_ADDRESS);

// ─────────────────────────────────────────────────────────────────────────────

/**
 * Returns an ethers Contract instance connected to the given signer or provider.
 * @param {ethers.Signer|ethers.Provider} signerOrProvider
 */
export function getArbitContract(signerOrProvider) {
    return new ethers.Contract(CONTRACT_ADDRESS, ABI, signerOrProvider);
}

/**
 * Creates a project on-chain by depositing HSK into escrow.
 * @param {ethers.Signer} signer
 * @param {number} thresholdInt AI score threshold (1–100)
 * @param {number|string} amountHsk Amount of HSK to lock
 * @returns {Promise<string>} Transaction hash
 */
export async function createProjectOnChain(signer, thresholdInt, amountHsk) {
    const contract = getArbitContract(signer);
    const value = ethers.parseEther(String(amountHsk));
    console.log(`[ArbitContract] Creating project: threshold=${thresholdInt}, value=${amountHsk} HSK`);

    const tx = await contract.createProject(thresholdInt, { value });
    console.log('[ArbitContract] TX broadcasted:', tx.hash);
    await tx.wait();
    console.log('[ArbitContract] ✓ TX confirmed:', tx.hash);
    return tx.hash;
}

/**
 * Submits milestone proof text to the blockchain.
 * @param {ethers.Signer} signer
 * @param {number} projectId On-chain project ID
 * @param {string} proofString Proof content
 * @returns {Promise<string>} Transaction hash
 */
export async function submitProofOnChain(signer, projectId, proofString) {
    const contract = getArbitContract(signer);
    console.log(`[ArbitContract] Submitting proof for project #${projectId}`);

    const tx = await contract.submitMilestoneProof(projectId, proofString);
    console.log('[ArbitContract] TX broadcasted:', tx.hash);
    await tx.wait();
    console.log('[ArbitContract] ✓ TX confirmed:', tx.hash);
    return tx.hash;
}

/**
 * AI Oracle submits a score. MUST be called by the oracle wallet (onlyOracle modifier).
 * @param {ethers.Signer} oracleSigner The oracle wallet signer
 * @param {number} projectId On-chain project ID
 * @param {number} score Score (0–100)
 * @returns {Promise<string>} Transaction hash
 */
export async function submitScoreOnChain(oracleSigner, projectId, score) {
    const contract = getArbitContract(oracleSigner);
    console.log(`[ArbitContract] Oracle submitting score=${score} for project #${projectId}`);

    // signature is reserved for future ECDSA oracle auth; pass '0x' for now
    const tx = await contract.submitAIScore(projectId, score, '0x');
    console.log('[ArbitContract] TX broadcasted:', tx.hash);
    await tx.wait();
    console.log('[ArbitContract] ✓ TX confirmed:', tx.hash);
    return tx.hash;
}

/**
 * Releases funds to the creator. Requires the oracle to have already submitted a passing score.
 * @param {ethers.Signer} signer Any connected wallet signer
 * @param {number} projectId On-chain project ID
 * @returns {Promise<string>} Transaction hash
 */
export async function releaseFundsOnChain(signer, projectId) {
    const contract = getArbitContract(signer);
    console.log(`[ArbitContract] Releasing funds for project #${projectId}`);

    const tx = await contract.releaseFunds(projectId);
    console.log('[ArbitContract] TX broadcasted:', tx.hash);
    await tx.wait();
    console.log('[ArbitContract] ✓ TX confirmed:', tx.hash);
    return tx.hash;
}

/**
 * Refunds locked HSK to the creator when score < threshold or not yet scored.
 * @param {ethers.Signer} signer Creator's wallet signer
 * @param {number} projectId On-chain project ID
 * @returns {Promise<string>} Transaction hash
 */
export async function refundOnChain(signer, projectId) {
    const contract = getArbitContract(signer);
    console.log(`[ArbitContract] Requesting refund for project #${projectId}`);

    const tx = await contract.refund(projectId);
    console.log('[ArbitContract] TX broadcasted:', tx.hash);
    await tx.wait();
    console.log('[ArbitContract] ✓ TX confirmed:', tx.hash);
    return tx.hash;
}
